NorthwindLevelTwo_Entity/MvcWebUI/Models/CartListViewModel.cs
using Entities.DomainModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcWebUI.Models
{
    public class CartListViewModel
    {
        public Cart Cart { get; set; }

    }
}

NorthwindLevelTwo_Entity/MvcWebUI/Models/CategoryListViewModel.cs
using Entities.Concreate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcWebUI.Models
{
    public class CategoryListViewModel
    {

        public List<Category> Categories { get; set; }
        public int CurrentCategory { get; set; }
    }
}

NorthwindLevelTwo_Entity/MvcWebUI/Models/ErrorViewModel.cs
using System;

namespace MvcWebUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NorthwindLevelTwo_Entity/MvcWebUI/Models/ProductListViewModel.cs
using Entities.Concreate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcWebUI.Models
{
    public class ProductListViewModel
    {
        public List<Product> Products { get; set; }

    }
}

NorthwindLevelTwo_Entity/MvcWebUI/Models/ShippingDetail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MvcWebUI.Models
{
    public class ShippingDetail
    {
        //[Required(ErrorMessage ="İsim gerekli")]//Alan boş geçilemez
        public string FirstName { get; set; }
        //[Required]
        public string LastName { get; set; }
        //[Required]
        //[DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        //[Required]
        public string City { get; set; }
        //[Required]
        public string Address { get; set; }
        //[Required]
        //[Range(18,65)]//18 min 65 max yaş değer aralığı
        public int Age { get; set; }


    }
}

NorthwindLevelTwo_Entity/MvcWebUI/Models/ShippingDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcWebUI.Models
{
    public class ShippingDetailsViewModel
    {
        public ShippingDetail ShippingDetail { get; set; }

    }
}

NorthwindLevelTwo_Entity/MvcWebUI/Controllers/CartController.cs
using Business.Abstract;
using Entities.Concreate;
using Microsoft.AspNetCore.Mvc;
using MvcWebUI.Helpers;
using MvcWebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcWebUI.Controllers
{
    public class CartController:Controller
    {
        private ICartService _cartService;
        private ICartSessionHelper _cartSessionHelper;
        private IProductService _productService;
        public CartController(ICartService cartService,ICartSessionHelper cartSessionHelper,IProductService productService)
        {
            _cartService = cartService;
            _cartSessionHelper = cartSessionHelper;
            _productService = productService;
            
        }

        public IActionResult AddToCart(int productId)
        {
            //Ürünü çek
            Product product = _productService.GetById(productId);
            var cart = _cartSessionHelper.GetCart("cart");
            _cartService.AddToCart(cart, product);
            _cartSessionHelper.SetCart("cart", cart);

            TempData.Add("message",product.ProductName+" sepete eklendi ...");

            return RedirectToAction("Index", "Product");
        }

        public IActionResult Index()
        {
            var model = new CartListViewModel
            {
                Cart = _cartSessionHelper.GetCart("cart")
            };
            
            return View(model);
        }
        
        public IActionResult RemoveFromCart(int productId)
        {
            Product product = _productService.GetById(productId);
            var cart = _cartSessionHelper.GetCart("cart");
            _cartService.RemoveFromCart(cart,productId);
            _cartSessionHelper.SetCart("cart",cart);
            TempData.Add("message",product.ProductName+" sepette silindi ...");

            return RedirectToAction("Index","Cart");

        }

        public IActionResult Comlete()
        {
            var model = new ShippingDetailsViewModel
            {
                ShippingDetail=new ShippingDetail()
            };
            return View();
        }

        [HttpPost]
        public IActionResult Complete(ShippingDetail shippingDetail)
        {
            if (ModelState.IsValid)
            {
                return View();
            }
            else
            {
                TempData.Add("message", "Siparişiniz başarıyla tamamlandı");
                _cartSessionHelper.Clear();

                return RedirectToAction("Index", "Cart");
            }
            
        }

        
    }
}

NorthwindLevelTwo_Entity/MvcWebUI/Controllers/CategoryController.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using MvcWebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcWebUI.Controllers
{
    public class CategoryController:Controller
    {
        private ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        //public IActionResult Index()
        //{
        //    var model = new CategoryListViewModel
        //    {
        //        Categories = _categoryService.GetAll()
        //    };

        //    return View(model);
        //}

    }
}

NorthwindLevelTwo_Entity/MvcWebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MvcWebUI.Models;

namespace MvcWebUI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NorthwindLevelTwo_Entity/MvcWebUI/Controllers/ProductController.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using MvcWebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcWebUI.Controllers
{
    public class ProductController:Controller
    {
        private IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Index(int category)
        {
            var model = new ProductListViewModel
            {
                Products = category>0?_productService.GetByCategory(category):_productService.GetAll()
                //category 0 ise bunu dğilse tümünü listele
                
            };
        
            return View(model);
        }
        
    }
}

NorthwindLevelTwo_Entity/MvcWebUI/ViewComponents/CategoryListViewComponent.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using MvcWebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcWebUI.ViewComponents
{
    public class CategoryListViewComponent:ViewComponent
    {
        private ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public ViewViewComponentResult Invoke()
        {
            var model = new CategoryListViewModel
            {
                Categories = _categoryService.GetAll(),

                CurrentCategory=Convert.ToInt32(HttpContext.Request.Query["category"]) 
            };

            return View(model);
        }
    }
}

NorthwindLevelTwo_Entity/MvcWebUI/Views/Cart/Comlete.cshtml
@model ShippingDetailsViewModel

<form asp-controller="Cart" asp-action="Complete" method="post">

    <div class="form-group">
        <label asp-for="ShippingDetail.FirstName">Ad</label>
        <input asp-for="ShippingDetail.FirstName" class="form-control" placeholder="Müşteri Adı" />
        <span asp-validation-for="ShippingDetail.FirstName"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShippingDetail.LastName">Soyad</label>
        <input asp-for="ShippingDetail.LastName" class="form-control" placeholder="Müşteri Soyadı" />
        <span asp-validation-for="ShippingDetail.LastName"></span>

    </div>
    <div class="form-group">
        <label asp-for="ShippingDetail.Email">Email</label>
        <input asp-for="ShippingDetail.Email" class="form-control" placeholder="Müşteri Email Adresi" />
        <span asp-validation-for="ShippingDetail.Email"></span>

    </div>
    <div class="form-group">
        <label asp-for="ShippingDetail.Age">Age</label>
        <input asp-for="ShippingDetail.Age" class="form-control" placeholder="Müşteri Yaşı" />
        <span asp-validation-for="ShippingDetail.Age"></span>

    </div>
    <div class="form-group">
        <label asp-for="ShippingDetail.City">Şehir</label>
        <input asp-for="ShippingDetail.City" class="form-control" placeholder="Şehir" />
        <span asp-validation-for="ShippingDetail.City"></span>

    </div>

    <div class="form-group">
        <label asp-for="ShippingDetail.Address">Adres</label>
        <input asp-for="ShippingDetail.Address" class="form-control" placeholder="Adres" />
        <span asp-validation-for="ShippingDetail.Address"></span>

    </div>

    <input type="submit" value="Kaydet" class="btn btn-success btn-sm"/>



</form>

NorthwindLevelTwo_Entity/MvcWebUI/Views/Cart/Index.cshtml
@model CartListViewModel

<h2>Sepetiniz</h2>

@if (Model.Cart.CartLines.Count == 0)
{
    <h2 class="badge badge-danger">Sepetiniz boş</h2>
}
else
{

    <table class="table table-responsive">

        <thead>
            <tr>
                <th>Id</th>
                <th>Ürün Adı</th>
                <th>Açıklama</th>
                <th>Fiyat</th>
                <th>Stok Adedi</th>
                <th>Satş Adedi</th>

            </tr>
        </thead>

        @foreach (var cartLine in Model.Cart.CartLines)
        {

            <tbody>
                <tr>
                    <td>@cartLine.Product.ProductId</td>
                    <td>@cartLine.Product.ProductName</td>
                    <td>@cartLine.Product.QuantityPerUnit</td>
                    <td>@cartLine.Product.UnitPrice</td>
                    <td>@cartLine.Product.UnitsInStock</td>
                    <td>@cartLine.Quantity</td>
                    <td><a class="btn btn-sm btn-danger" asp-controller="Cart" asp-action="RemoveFromCart" asp-route-productId="@cartLine.Product.ProductId">Sil</a></td>


                </tr>
            </tbody>


        }

    </table>
}

NorthwindLevelTwo_Entity/MvcWebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

NorthwindLevelTwo_Entity/MvcWebUI/Views/Product/Index.cshtml
@model ProductListViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "_Layout";
}

<h2>Ürünler</h2>
<table class="table table-responsive">

    @foreach (var item in Model.Products)
    {
        <tr>
            <td>@item.ProductId</td>
            <td>@item.ProductName</td>
            <td>@item.QuantityPerUnit</td>
            <td>@item.UnitPrice</td>
            <td>@item.UnitsInStock</td>
            <td><a class="btn btn-sm btn-success" asp-controller="Cart" asp-action="AddToCart" asp-route-productId="@item.ProductId">Sepete Ekle</a></td>
        </tr>
    }

</table>

NorthwindLevelTwo_Entity/MvcWebUI/Views/Shared/Components/CategoryList/Default.cshtml
@model CategoryListViewModel


<h2>Kategoriler</h2>
<div class="list-group">

    <a href="/product/index" class="list-group-item">Tümünü Listele</a>

    @foreach (var item in Model.Categories)
    {
        var css = "list-group-item";
        if (item.CategoryId == Model.CurrentCategory)
        {
            css += " active";
        }

        <a href="/product/index?category=@item.CategoryId" class="@css">@item.CategoryName </a>
    }

</div>

NorthwindLevelTwo_Entity/MvcWebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcWebUI</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MvcWebUI</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Product" asp-action="Index">Anasayfa</a></li>
                    <li><a asp-area="" asp-controller="Cart" asp-action="Index">Sepete Git</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">

        <div class="row">
            @if (TempData["message"] !=null)
            {
                <div class="alert alert-info">
                    @TempData["message"]
                </div>
            }
        </div>
        <div class="row">
            <div class="col-lg-3">
                 @await Component.InvokeAsync("CategoryList")

            </div>
            <div class="col-lg-9">@RenderBody()</div>
        </div>
        <hr />
        <footer>
            <p>&copy; 2020 - MvcWebUI</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>